# تشغيل
PORT=5000
INTERVAL=15m
SYMBOL=DOGE/USDT:USDT
LEVERAGE=10
RISK_PCT=60

# دخول من TV فقط
FORCE_TV_ENTRIES=true
USE_TV_BAR=true

# مؤشرات
RSI_LEN=14
ADX_LEN=14
ATR_LEN=14

# إدارة ذكية
TP1_PCT=0.40
TP1_CLOSE_FRAC=0.50
BREAKEVEN_AFTER_PCT=0.30
TRAIL_ACTIVATE_PCT=0.60
ATR_MULT_TRAIL=1.6
HOLD_TP_STRONG=true
HOLD_TP_ADX=28
HOLD_TP_SLOPE=0.50

# Scale-In
SCALE_IN_ENABLED=true
SCALE_IN_ADX_MIN=22
SCALE_IN_SLOPE_MIN=0.35
SCALE_IN_MAX_ADDS=3

# مرشحات
RANGE_MIN_PCT=1.0
SPIKE_FILTER_ATR_MULTIPLIER=2.2
MOVE_3BARS_PCT=0.8

# HUD / Logs
LOG_STYLE=classic
LOG_ICONS=true
LOG_COLORS=true
LOG_SHOW_INDICATORS=true
LOG_SHOW_POSITION=true
LOG_SHOW_RESULTS=true
LOG_SHOW_NEXT_ORDER=true
KEEPALIVE_SECONDS=50
